language: Java
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
- ./gradlew sonarqube
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: heroku
  api_key:
    secure: CyIzfw+7ukLVn67VuRH5ovxRdbjzpRwi6joXbwgYvaCi26zcyLnH8ylUQZny89ZdZFHmF9GEa2JWjjB9lCd1pv3GOC0TuezlonT9d2OPWGh3RTSHj07ulzjP9g4NtH0I39uHDIRbOWCZxiywY49k6o4J6PlfN27bC8s4l1WrzPYm6A+5K2/iW2a7sm29JSt/QZrCRT4OtHawhY5CtZnd9yjlAqzWJx+g7JSqdFnnc7qqNsQIa7dl+5HW88or+WkJiVtd45EU25gvb9DoVp2SRH45LUa2imKJeuY6fg0xnjYdUbeLqu7doBWnlnMT9Js0+5nMSjvJfkHnvl0sv9ckFOyQXbdqaV5JyLBNV+UZtvqIklSbk1SN4YZb59Rui/UrwuUbRjn/jJu1yxdlbkoUED/AA872FOUepC7XSaHNhI3Va4PIb7qggxCloYHiToKNgl96011pUB4aV78vQ+NrYuwMqTf03RR6L60L6LxUoAt7t0kMRuB6/wpHpXSH3s0GWaagdzbKMVXkbtxAZXOTn+KW3SklfY2lTpKdPyIwD5p2lWcZDab8tUuL2G60nb58Wegkca5kFBOkfma+HC6tBzpSEZO+nOBHU5FiBnz9F7H9vzy/quG52L/Jy/rTfrmD/ItYCnQgzXm38TcWbwOkoQSWTQVwvma9rH3ZcujUGQ4=
  app: market-data-service-staging
  skip_cleanup: true
  on:
    repo: spolnik/trading-office-market-data-service
